### ISSUE TITLE
Photos.

### ISSUE THREAD

**Issue by Kimsjoberg99** [mirrox1337/Telefon#4]
As I wrote earlier, how do i take photos? and is the src_htmlPhone needed, if so how to i make it work correctly?

**Comment by mirrox1337** [comment]
You will need screenshot-basic

**Comment by Kimsjoberg99** [comment]
I keep getting the same error as a lot of others. '' Could not start dependency webpack for resource screenshot-basic '' and i've found no fix for it. Hmm

**Comment by Kimsjoberg99** [comment]
Also a lot of people get only black photos.

**Comment by mirrox1337** [comment]
I can't give any support on Screenshot-basic. sorry
